### ISSUE TITLE
我试了下py32F003 的工程可以直接用哦

### ISSUE THREAD

**Issue by songzhishuo** [kaidegit/air001-cmake#1]
我试了下IOSetting 的py32F003 的Makefile 的Demo 是可以直接用的，是不是可以直接依赖于这个项目做开发会快点。我直接用AirISP下载测试了下是ok的。
https://github.com/IOsetting/py32f0-template

**Comment by kaidegit** [comment]
就是因为不喜欢用makefile才搓一个cmake来的。。。
