### ISSUE TITLE
HAL_Delay无法正常使用

### ISSUE THREAD

**Issue by SendToSouthEast** [kaidegit/air001-cmake#2]
首先感谢您建立Cmake项目，不用我自己造轮子了……
跑了个闪灯demo，但是发现灯不能正常闪烁，经过排查，发现HAL_Delay函数即使填10也无法正常延时，而是无限长（至少我没等到闪烁）
arm-none-eabi-gcc版本：12.2.1
烧录软件：AirIsp
烧录命令：AirISP.exe -c air001 -p COM21 -b 115200 write_flash -e 0x08000000 Air001_CMake.hex
测试代码：
`mian.c`
```
#include "main.h"

#include "air001xx_hal.h"

int main(void)
{
    HAL_Init();
    GPIO_InitTypeDef GPIO_LED = {
            .Pin = GPIO_PIN_1,
            .Mode = GPIO_MODE_OUTPUT_PP,
    };
    __HAL_RCC_GPIOB_CLK_ENABLE();
    HAL_GPIO_Init(GPIOB, &GPIO_LED);

    GPIO_InitTypeDef GPIO_LED2 = {
            .Pin = GPIO_PIN_0,
            .Mode = GPIO_MODE_OUTPUT_PP,
    };
    HAL_GPIO_Init(GPIOB, &GPIO_LED2);

    while (1)
    {
        HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
        HAL_Delay(10);
        HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_0);
        HAL_Delay(10);
    }
}
```

**Comment by SendToSouthEast** [comment]
暂停程序，一直在这个位置
![image](https://github.com/kaidegit/air001-cmake/assets/93421418/e045a96d-5302-4ea7-8411-22d0a6b78705)
![image](https://github.com/kaidegit/air001-cmake/assets/93421418/c39393fc-1fcd-4db4-bccc-a0a718c6cc2b)

**Comment by kaidegit** [comment]
在`HAL_Init()`前，或者是在`HAL_MspInit`里
```
    __HAL_RCC_SYSCFG_CLK_ENABLE();
    __HAL_RCC_PWR_CLK_ENABLE();
```
了嘛

**Comment by kaidegit** [comment]
emm我忘记推我后面稍微改过的版本了，稍微等下

**Comment by kaidegit** [comment]
主要问题应该是`SysTick_Handler`的回调没写。。

**Comment by kaidegit** [comment]
应该修好了
